"""Add new column to Student table

Revision ID: 1d8d517f1d7b
Revises: dcc03bb3fd6a
Create Date: 2022-11-06 21:54:11.751802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8d517f1d7b'
down_revision = 'dcc03bb3fd6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'is_deleted')
    # ### end Alembic commands ###
